var myMap = new Map();
console.log("mymap생성");

myMap.set("United States of America", "us");
myMap.set("Argentina", "ar"); 
myMap.set("Australia", "au"); 
myMap.set("Austria", "at"); 
myMap.set("Belgium", "be"); 
myMap.set("Brazil", "br"); 
myMap.set("Bulgaria", "bg"); 
myMap.set("Canada", "ca"); 
myMap.set("China", "cn"); 
myMap.set("Colombia", "co"); 
myMap.set("Cuba", "cu"); 
myMap.set("Czech Republic", "cz"); 
myMap.set("Egygt", "eg"); 
myMap.set("France", "fr"); 
myMap.set("Germany", "de"); 
myMap.set("Greece", "gr"); 
myMap.set("Hong Kong", "hk"); 
myMap.set("India", "in"); 
myMap.set("Ireland", "ie"); 
myMap.set("Israel", "il"); 
myMap.set("Italy", "it"); 
myMap.set("Japan", "jp"); 
myMap.set("Latvia", "lv"); 
myMap.set("Lithuania", "lt"); 
myMap.set("Malaysia", "my"); 
myMap.set("Mexico", "mx"); 
myMap.set("Morocco", "ma"); 
myMap.set("Netherlands", "nl"); 
myMap.set("New Zealand", "nz"); 
myMap.set("Nigeria", "ng"); 
myMap.set("Norway", "no"); 
myMap.set("Philppines", "ph"); 
myMap.set("Poland", "pl"); 
myMap.set("Portugal", "pt"); 
myMap.set("Romania", "ro"); 
myMap.set("Russia", "ru");
myMap.set("Saudi Arabia", "sa"); 
myMap.set("Serbia", "rs"); 
myMap.set("Singapore", "sg"); 
myMap.set("Slovakia", "sk");
myMap.set("Slovenia", "si"); 
myMap.set("South Africa", "za"); 
myMap.set("South Korea", "kr"); 
myMap.set("Sweden", "se");
myMap.set("Switzerland", "ch"); 
myMap.set("Taiwan", "tw"); 
myMap.set("Thailand", "th"); 
myMap.set("Turkey", "tr"); 
myMap.set("UAE", "ae"); 
myMap.set("Ukraine", "ua"); 
myMap.set("United Kingdom", "gb");
myMap.set("United States", "us");
myMap.set("Venuzuela", "ve"); 